import { Inter, Roboto_Mono } from "next/font/google";
import "../globals.css";
import Header from "../components/header";
import Footer from "../components/footer";
import { getRequestInfo } from "../utils/getRequestInfo";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const { isMobile } = getRequestInfo();
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable}`}>
        <Header isMobile={isMobile} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
