export default function Search() {
  return (
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Date</th>
          <th>Date</th>
          <th>Date</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>20-02-25</td>
          <td>25</td>
          <td>20</td>
          <td>02</td>
        </tr>
        <tr>
          <td>20-02-25</td>
          <td>25</td>
          <td>20</td>
          <td>02</td>
        </tr>
        <tr>
          <td>20-02-25</td>
          <td>25</td>
          <td>20</td>
          <td>02</td>
        </tr>
        <tr>
          <td>20-02-25</td>
          <td>25</td>
          <td>20</td>
          <td>02</td>
        </tr>
        <tr>
          <td>20-02-25</td>
          <td>25</td>
          <td>20</td>
          <td>02</td>
        </tr>
      </tbody>
    </table>
  );
}
